name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/jekyll container (Debian-based)
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/srv/jekyll \
          -e JEKYLL_ENV=production \
          -w /srv/jekyll \
          jekyll/builder \
          bash -c "
            chmod -R a+w /srv/jekyll && \
            bundle install && \
            jekyll build --future
          "
