name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/jekyll container (Debian-based)
      run: |
        - name: Build site using Ruby image
  run: |
    docker run --rm \
      -v ${{ github.workspace }}:/srv/jekyll \
      -w /srv/jekyll \
      ruby:3.2-bullseye \
      bash -c "
        apt-get update && \
        apt-get install -y build-essential libffi-dev ruby-dev git && \
        gem install bundler && \
        bundle install && \
        bundle exec jekyll build --future"
